# Generated by Django 4.1.7 on 2023-04-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookmarks", "0005_alter_bookmark_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="title")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PG", "Pending"),
                            ("CD", "Completed"),
                            ("FD", "Failed"),
                        ],
                        default="PG",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="file")),
                ("file_size", models.IntegerField(verbose_name="file size, bytes")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "bookmark",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="bookmarks.bookmark",
                        verbose_name="bookmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "download",
                "verbose_name_plural": "downloads",
                "ordering": ["-created"],
            },
        ),
    ]
