# Generated by Django 4.1.7 on 2023-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="download",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="file_size",
            field=models.IntegerField(default=0, verbose_name="file size, bytes"),
        ),
        migrations.AlterField(
            model_name="download",
            name="title",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="title"
            ),
        ),
    ]
