# Generated by Django 4.1.7 on 2023-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0002_alter_bookmark_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="read"),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.CharField(max_length=256, verbose_name="title"),
        ),
    ]
