# Generated by Django 4.1.7 on 2023-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="telegram id"
            ),
        ),
    ]
