# Generated by Django 4.1.7 on 2023-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="disk_quota",
            field=models.IntegerField(default=0, verbose_name="disk quota, Mb"),
        ),
    ]
